# Generated by Django 4.1.1 on 2022-12-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_p1',
            name='head_img',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='m_p1',
            name='main_thesis1',
            field=models.CharField(default='Best solution', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p1',
            name='main_thesis2',
            field=models.CharField(default='Best choice', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p1',
            name='main_title',
            field=models.CharField(default='Sneaker', max_length=30),
        ),
        migrations.AddField(
            model_name='m_p1',
            name='main_title_downer',
            field=models.CharField(default='Name Product', max_length=30),
        ),
        migrations.AddField(
            model_name='m_p1',
            name='quote',
            field=models.CharField(default='The best product that I have ever ordered', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p1',
            name='text_about_product',
            field=models.TextField(default='First description about product'),
        ),
        migrations.AddField(
            model_name='m_p1',
            name='title_down',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='m_p1',
            name='tittle_descr',
            field=models.CharField(default='It does not have analogs', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p2',
            name='head_img',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='m_p2',
            name='main_thesis1',
            field=models.CharField(default='Best solution', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p2',
            name='main_thesis2',
            field=models.CharField(default='Best choice', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p2',
            name='main_title',
            field=models.CharField(default='Sneaker', max_length=30),
        ),
        migrations.AddField(
            model_name='m_p2',
            name='main_title_downer',
            field=models.CharField(default='Name Product', max_length=30),
        ),
        migrations.AddField(
            model_name='m_p2',
            name='quote',
            field=models.CharField(default='The best product that I have ever ordered', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p2',
            name='text_about_product',
            field=models.TextField(default='First description about product'),
        ),
        migrations.AddField(
            model_name='m_p2',
            name='title_down',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='m_p2',
            name='tittle_descr',
            field=models.CharField(default='It does not have analogs', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p3',
            name='head_img',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='m_p3',
            name='main_thesis1',
            field=models.CharField(default='Best solution', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p3',
            name='main_thesis2',
            field=models.CharField(default='Best choice', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p3',
            name='main_title',
            field=models.CharField(default='Sneaker', max_length=30),
        ),
        migrations.AddField(
            model_name='m_p3',
            name='main_title_downer',
            field=models.CharField(default='Name Product', max_length=30),
        ),
        migrations.AddField(
            model_name='m_p3',
            name='quote',
            field=models.CharField(default='The best product that I have ever ordered', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p3',
            name='text_about_product',
            field=models.TextField(default='First description about product'),
        ),
        migrations.AddField(
            model_name='m_p3',
            name='title_down',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='m_p3',
            name='tittle_descr',
            field=models.CharField(default='It does not have analogs', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p4',
            name='head_img',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='m_p4',
            name='main_thesis1',
            field=models.CharField(default='Best solution', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p4',
            name='main_thesis2',
            field=models.CharField(default='Best choice', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p4',
            name='main_title',
            field=models.CharField(default='Sneaker', max_length=30),
        ),
        migrations.AddField(
            model_name='m_p4',
            name='main_title_downer',
            field=models.CharField(default='Name Product', max_length=30),
        ),
        migrations.AddField(
            model_name='m_p4',
            name='quote',
            field=models.CharField(default='The best product that I have ever ordered', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p4',
            name='text_about_product',
            field=models.TextField(default='First description about product'),
        ),
        migrations.AddField(
            model_name='m_p4',
            name='title_down',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='m_p4',
            name='tittle_descr',
            field=models.CharField(default='It does not have analogs', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p5',
            name='head_img',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='m_p5',
            name='main_thesis1',
            field=models.CharField(default='Best solution', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p5',
            name='main_thesis2',
            field=models.CharField(default='Best choice', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p5',
            name='main_title',
            field=models.CharField(default='Sneaker', max_length=30),
        ),
        migrations.AddField(
            model_name='m_p5',
            name='main_title_downer',
            field=models.CharField(default='Name Product', max_length=30),
        ),
        migrations.AddField(
            model_name='m_p5',
            name='quote',
            field=models.CharField(default='The best product that I have ever ordered', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p5',
            name='text_about_product',
            field=models.TextField(default='First description about product'),
        ),
        migrations.AddField(
            model_name='m_p5',
            name='title_down',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='m_p5',
            name='tittle_descr',
            field=models.CharField(default='It does not have analogs', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p6',
            name='head_img',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='m_p6',
            name='main_thesis1',
            field=models.CharField(default='Best solution', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p6',
            name='main_thesis2',
            field=models.CharField(default='Best choice', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p6',
            name='main_title',
            field=models.CharField(default='Sneaker', max_length=30),
        ),
        migrations.AddField(
            model_name='m_p6',
            name='main_title_downer',
            field=models.CharField(default='Name Product', max_length=30),
        ),
        migrations.AddField(
            model_name='m_p6',
            name='quote',
            field=models.CharField(default='The best product that I have ever ordered', max_length=100),
        ),
        migrations.AddField(
            model_name='m_p6',
            name='text_about_product',
            field=models.TextField(default='First description about product'),
        ),
        migrations.AddField(
            model_name='m_p6',
            name='title_down',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='m_p6',
            name='tittle_descr',
            field=models.CharField(default='It does not have analogs', max_length=100),
        ),
        migrations.AlterField(
            model_name='m_p1',
            name='title',
            field=models.CharField(default='Unforgettable', max_length=30),
        ),
        migrations.AlterField(
            model_name='m_p2',
            name='title',
            field=models.CharField(default='Unforgettable', max_length=30),
        ),
        migrations.AlterField(
            model_name='m_p3',
            name='title',
            field=models.CharField(default='Unforgettable', max_length=30),
        ),
        migrations.AlterField(
            model_name='m_p4',
            name='title',
            field=models.CharField(default='Unforgettable', max_length=30),
        ),
        migrations.AlterField(
            model_name='m_p5',
            name='title',
            field=models.CharField(default='Unforgettable', max_length=30),
        ),
        migrations.AlterField(
            model_name='m_p6',
            name='title',
            field=models.CharField(default='Unforgettable', max_length=30),
        ),
    ]
