# Generated by Django 4.1.1 on 2022-12-14 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0002_m_p1_head_img_m_p1_main_thesis1_m_p1_main_thesis2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='M_P5',
            new_name='More_inform1',
        ),
        migrations.RenameModel(
            old_name='M_P2',
            new_name='More_inform2',
        ),
        migrations.RenameModel(
            old_name='M_P3',
            new_name='More_inform3',
        ),
        migrations.RenameModel(
            old_name='M_P1',
            new_name='More_inform4',
        ),
        migrations.RenameModel(
            old_name='M_P6',
            new_name='More_inform5',
        ),
        migrations.RenameModel(
            old_name='M_P4',
            new_name='More_inform6',
        ),
    ]
