# Generated by Django 4.1.1 on 2022-12-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0003_rename_m_p5_more_inform1_rename_m_p2_more_inform2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='text1_1',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='products',
            name='text1_2',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='products',
            name='text2_1',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='products',
            name='text2_2',
            field=models.CharField(default='', max_length=25),
        ),
    ]
