# Generated by Django 4.1.1 on 2022-12-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0004_alter_products_text1_1_alter_products_text1_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='text1_1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='text1_2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='text2_1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='text2_2',
        ),
        migrations.AddField(
            model_name='products',
            name='name1',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='products',
            name='name2',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='products',
            name='name3',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='products',
            name='name4',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='products',
            name='name5',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='products',
            name='name6',
            field=models.CharField(default='', max_length=25),
        ),
    ]
