# Generated by Django 4.1.1 on 2022-12-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0006_remove_contact_adres_remove_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='more_inform1',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='more_inform2',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='more_inform3',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='more_inform4',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='more_inform5',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='more_inform6',
            name='descr',
        ),
    ]
