# Generated by Django 4.1.1 on 2022-12-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0007_remove_more_inform1_descr_remove_more_inform2_descr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='more_inform1',
            name='title_down',
        ),
        migrations.RemoveField(
            model_name='more_inform2',
            name='title_down',
        ),
        migrations.RemoveField(
            model_name='more_inform3',
            name='title_down',
        ),
        migrations.RemoveField(
            model_name='more_inform4',
            name='title_down',
        ),
        migrations.RemoveField(
            model_name='more_inform5',
            name='title_down',
        ),
        migrations.RemoveField(
            model_name='more_inform6',
            name='title_down',
        ),
    ]
