# Generated by Django 4.1.1 on 2023-07-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0010_contact_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="main2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_title", models.CharField(default="Sneaker", max_length=30)),
                (
                    "main_thesis1",
                    models.CharField(default="Best solution", max_length=100),
                ),
                (
                    "main_thesis2",
                    models.CharField(default="Best choice", max_length=100),
                ),
                (
                    "main_title_downer",
                    models.CharField(default="Name Product", max_length=30),
                ),
                (
                    "text_about_product",
                    models.TextField(default="First description about product"),
                ),
                ("head_img", models.ImageField(default="", upload_to="")),
                (
                    "quote",
                    models.CharField(
                        default="The best product that I have ever ordered",
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(default="Unforgettable", max_length=30)),
                (
                    "tittle_descr",
                    models.CharField(
                        default="It does not have analogs", max_length=100
                    ),
                ),
                ("main_img", models.ImageField(default="", upload_to="")),
                ("image1", models.ImageField(default="", upload_to="")),
                ("image2", models.ImageField(default="", upload_to="")),
                ("image3", models.ImageField(default="", upload_to="")),
                ("text1_1", models.TextField(default="")),
                ("text1_2", models.TextField(default="")),
                ("text1_3", models.TextField(default="")),
                ("text2_1", models.TextField(default="")),
                ("text2_2", models.TextField(default="")),
                ("text2_3", models.TextField(default="")),
                ("text3_1", models.TextField(default="")),
                ("text3_2", models.TextField(default="")),
                ("text3_3", models.TextField(default="")),
            ],
        ),
        migrations.DeleteModel(
            name="About_us",
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.DeleteModel(
            name="More_inform1",
        ),
        migrations.DeleteModel(
            name="More_inform2",
        ),
        migrations.DeleteModel(
            name="More_inform3",
        ),
        migrations.DeleteModel(
            name="More_inform4",
        ),
        migrations.DeleteModel(
            name="More_inform5",
        ),
        migrations.DeleteModel(
            name="More_inform6",
        ),
        migrations.DeleteModel(
            name="Sneakers",
        ),
    ]
