# Generated by Django 4.1.1 on 2023-07-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0011_main2_delete_about_us_delete_contact_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Products",
        ),
        migrations.RemoveField(
            model_name="main2",
            name="head_img",
        ),
        migrations.RemoveField(
            model_name="main2",
            name="main_img",
        ),
        migrations.RemoveField(
            model_name="main2",
            name="main_thesis1",
        ),
        migrations.RemoveField(
            model_name="main2",
            name="main_thesis2",
        ),
        migrations.RemoveField(
            model_name="main2",
            name="main_title",
        ),
        migrations.RemoveField(
            model_name="main2",
            name="main_title_downer",
        ),
        migrations.RemoveField(
            model_name="main2",
            name="quote",
        ),
        migrations.RemoveField(
            model_name="main2",
            name="text_about_product",
        ),
        migrations.RemoveField(
            model_name="main2",
            name="title",
        ),
        migrations.RemoveField(
            model_name="main2",
            name="tittle_descr",
        ),
        migrations.RemoveField(
            model_name="mainpage1_cross",
            name="text1_3",
        ),
        migrations.RemoveField(
            model_name="mainpage1_cross",
            name="text3_3",
        ),
        migrations.AddField(
            model_name="mainpage1_cross",
            name="text1_3_1",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="mainpage1_cross",
            name="text1_3_2",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="mainpage1_cross",
            name="text1_3_3",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="mainpage1_cross",
            name="text3_3_1",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="mainpage1_cross",
            name="text3_3_2",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="mainpage1_cross",
            name="text3_3_3",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="mainpage1_cross",
            name="text3_3_4",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="main2",
            name="image1",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="main2",
            name="image2",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="main2",
            name="image3",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="main2",
            name="text1_1",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="main2",
            name="text1_2",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="main2",
            name="text1_3",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="main2",
            name="text2_1",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="main2",
            name="text2_2",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="main2",
            name="text2_3",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="main2",
            name="text3_1",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="main2",
            name="text3_2",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="main2",
            name="text3_3",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="mainpage1_cross",
            name="text1_1",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="mainpage1_cross",
            name="text1_2",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="mainpage1_cross",
            name="text2_1",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="mainpage1_cross",
            name="text2_2",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="mainpage1_cross",
            name="text2_3",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="mainpage1_cross",
            name="text3_1",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="mainpage1_cross",
            name="text3_2",
            field=models.CharField(max_length=900, null=True),
        ),
    ]
