# Generated by Django 4.1.1 on 2023-07-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0012_delete_products_remove_main2_head_img_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpage1_cross",
            name="text3_3_5",
            field=models.CharField(max_length=900, null=True),
        ),
    ]
