# Generated by Django 4.1.1 on 2023-07-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0013_mainpage1_cross_text3_3_5"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="main2",
            name="text1_3",
        ),
        migrations.RemoveField(
            model_name="main2",
            name="text3_3",
        ),
        migrations.AddField(
            model_name="main2",
            name="text1_3_1",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="main2",
            name="text1_3_2",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="main2",
            name="text1_3_3",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="main2",
            name="text3_3_1",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="main2",
            name="text3_3_2",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="main2",
            name="text3_3_3",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="main2",
            name="text3_3_4",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="main2",
            name="text3_3_5",
            field=models.CharField(max_length=900, null=True),
        ),
    ]
