# Generated by Django 4.1.1 on 2023-07-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0014_remove_main2_text1_3_remove_main2_text3_3_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainpage1_cross",
            name="text2_3",
        ),
        migrations.AddField(
            model_name="mainpage1_cross",
            name="text2_3_1",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="mainpage1_cross",
            name="text2_3_2",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="mainpage1_cross",
            name="text2_3_3",
            field=models.CharField(max_length=900, null=True),
        ),
    ]
