# Generated by Django 4.1.1 on 2023-07-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0016_remove_main2_text2_3_main2_text2_3_1_main2_text2_3_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpage1_cross",
            name="text1_3_4",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="mainpage1_cross",
            name="text1_3_5",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="mainpage1_cross",
            name="text1_3_6",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="mainpage1_cross",
            name="text1_3_7",
            field=models.CharField(max_length=900, null=True),
        ),
    ]
