# Generated by Django 4.1.1 on 2023-07-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0017_mainpage1_cross_text1_3_4_mainpage1_cross_text1_3_5_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="main2",
            name="text1_3_4",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="main2",
            name="text1_3_5",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="main2",
            name="text1_3_6",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="main2",
            name="text1_3_7",
            field=models.CharField(max_length=900, null=True),
        ),
    ]
