# Generated by Django 4.1.1 on 2023-07-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0018_main2_text1_3_4_main2_text1_3_5_main2_text1_3_6_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="main2",
            name="pre_image",
            field=models.ImageField(default="", upload_to=""),
        ),
        migrations.AddField(
            model_name="main2",
            name="pre_text",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="mainpage1_cross",
            name="pre_image",
            field=models.ImageField(default="", upload_to=""),
        ),
        migrations.AddField(
            model_name="mainpage1_cross",
            name="pre_text",
            field=models.CharField(max_length=900, null=True),
        ),
    ]
