# Generated by Django 4.1.1 on 2023-07-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0019_main2_pre_image_main2_pre_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="main2",
            name="button_for_page",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="mainpage1_cross",
            name="button_for_page",
            field=models.CharField(max_length=900, null=True),
        ),
    ]
