# Generated by Django 4.1.1 on 2023-07-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0020_main2_button_for_page_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="main2",
            name="pre_text",
        ),
        migrations.RemoveField(
            model_name="mainpage1_cross",
            name="pre_text",
        ),
        migrations.AddField(
            model_name="main2",
            name="pre_text1",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="main2",
            name="pre_text2",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="mainpage1_cross",
            name="pre_text1",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name="mainpage1_cross",
            name="pre_text2",
            field=models.CharField(max_length=900, null=True),
        ),
    ]
