# Generated by Django 4.1.1 on 2023-07-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0022_remove_main2_button_for_page_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="main2",
            name="pre_image",
            field=models.ImageField(
                default="img/1920x1080/samolet_chb_minimalizm_123291_1920x1080.jpg",
                upload_to="",
            ),
        ),
    ]
