# Generated by Django 4.1.1 on 2023-07-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0023_alter_main2_pre_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpage1_cross",
            name="pre_image",
            field=models.ImageField(
                default="img/1920x1080/samolet_chb_minimalizm_123291_1920x1080.jpg",
                upload_to="",
            ),
        ),
    ]
