# Generated by Django 4.1.1 on 2023-07-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0024_alter_mainpage1_cross_pre_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="main2",
            name="big_text",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="mainpage1_cross",
            name="big_text",
            field=models.TextField(null=True),
        ),
    ]
